export const SET_SCENE = 'SET_SCENE';
export const DESTROY_SCENE = 'DESTROY_SCENE';

export const SET_MAIN_CAMERA = 'SET_MAIN_CAMERA';
export const UPDATE_ASPECT_OF_MAIN_CAMERA = 'UPDATE_ASPECT_OF_MAIN_CAMERA';

export const SET_RENDERER = 'SET_RENDERER';
export const DESTROY_RENDERER = 'DESTROY_RENDERER';
export const SET_RENDERER_SIZE = 'SET_RENDERER_SIZE';

export const ADD_OBJECT = 'ADD_OBJECT';
export const REMOVE_ALL_OBJECTS = 'REMOVE_ALL_OBJECTS';
export const REMOVE_OBJECT_BY_NAME = 'REMOVE_OBJECT_BY_NAME';

export const SET_CONTROLS = 'SET_CONTROLS';
